// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAE1nQYbw2mDvPtJ3pYVism4p5mfc_Gk',
    appId: '1:341491368996:web:c9323233a1b652314384b1',
    messagingSenderId: '341491368996',
    projectId: 'chat-app-fb-data',
    authDomain: 'chat-app-fb-data.firebaseapp.com',
    storageBucket: 'chat-app-fb-data.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz6sjJwmzK5QgtjiaaMU6ZjspsUoxJy9Y',
    appId: '1:341491368996:android:1286cb2c232c21004384b1',
    messagingSenderId: '341491368996',
    projectId: 'chat-app-fb-data',
    storageBucket: 'chat-app-fb-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtMpVxiqi8G_0_rU_yQepf0w2SV-tTKAg',
    appId: '1:341491368996:ios:bf5b9dbc29e4e8c04384b1',
    messagingSenderId: '341491368996',
    projectId: 'chat-app-fb-data',
    storageBucket: 'chat-app-fb-data.appspot.com',
    iosBundleId: 'com.example.chatappFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtMpVxiqi8G_0_rU_yQepf0w2SV-tTKAg',
    appId: '1:341491368996:ios:bf5b9dbc29e4e8c04384b1',
    messagingSenderId: '341491368996',
    projectId: 'chat-app-fb-data',
    storageBucket: 'chat-app-fb-data.appspot.com',
    iosBundleId: 'com.example.chatappFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWAE1nQYbw2mDvPtJ3pYVism4p5mfc_Gk',
    appId: '1:341491368996:web:2cb18dcc2bb4d2ec4384b1',
    messagingSenderId: '341491368996',
    projectId: 'chat-app-fb-data',
    authDomain: 'chat-app-fb-data.firebaseapp.com',
    storageBucket: 'chat-app-fb-data.appspot.com',
  );
}
